export {default as Artical } from './Artical/Artical'
export {default as Brand} from './Brand/Brand'
export {default as CTA} from './CTA/CTA'
export {default as Featuares} from './Featuares/Featurns'
export {default as Navbar} from './Navbar/Navbar'